name: Java CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'temurin'
          java-version: 21
          
      - name: Cache local Gradle repository
        uses: actions/cache@v4.2.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew && ./gradlew build

      - uses: actions/upload-artifact@v4.6.0
        with:
          path: bin/*.jar
